PUZZLES = [
    # Thing
    ("BIRTHDAY CAKE", "Thing"),
    ("SWIMMING POOL", "Thing"),
    ("GARDEN HOSE", "Thing"),
    ("ALARM CLOCK", "Thing"),
    ("CEILING FAN", "Thing"),
    ("COFFEE MUG", "Thing"),
    ("BASKETBALL HOOP", "Thing"),
    ("FIRE EXTINGUISHER", "Thing"),
    ("ROCKING CHAIR", "Thing"),
    ("SNOW GLOBE", "Thing"),
    ("TELESCOPE", "Thing"),
    ("PIGGY BANK", "Thing"),
    ("DIVING BOARD", "Thing"),
    ("WELCOME MAT", "Thing"),
    ("MAGNIFYING GLASS", "Thing"),
    ("RUBBER DUCK", "Thing"),
    ("POCKET WATCH", "Thing"),
    ("WIND CHIME", "Thing"),
    ("LAVA LAMP", "Thing"),
    ("STAPLE GUN", "Thing"),
    ("IRONING BOARD", "Thing"),
    ("PAPER SHREDDER", "Thing"),
    ("DOOR KNOCKER", "Thing"),
    ("FISH TANK", "Thing"),
    ("THROW PILLOW", "Thing"),

    # Proper Name
    ("ALBERT EINSTEIN", "Proper Name"),
    ("MARIE CURIE", "Proper Name"),
    ("ABRAHAM LINCOLN", "Proper Name"),
    ("CLEOPATRA", "Proper Name"),
    ("LEONARDO DA VINCI", "Proper Name"),
    ("NEIL ARMSTRONG", "Proper Name"),
    ("WILLIAM SHAKESPEARE", "Proper Name"),
    ("MARTIN LUTHER KING", "Proper Name"),
    ("AMELIA EARHART", "Proper Name"),
    ("BENJAMIN FRANKLIN", "Proper Name"),
    ("ROSA PARKS", "Proper Name"),
    ("CHARLES DARWIN", "Proper Name"),
    ("FRIDA KAHLO", "Proper Name"),
    ("NIKOLA TESLA", "Proper Name"),
    ("HARRIET TUBMAN", "Proper Name"),
    ("NAPOLEON BONAPARTE", "Proper Name"),
    ("WINSTON CHURCHILL", "Proper Name"),
    ("MAHATMA GANDHI", "Proper Name"),
    ("EDGAR ALLAN POE", "Proper Name"),
    ("FLORENCE NIGHTINGALE", "Proper Name"),
    ("MARK TWAIN", "Proper Name"),
    ("ISAAC NEWTON", "Proper Name"),
    ("JOAN OF ARC", "Proper Name"),
    ("JULIUS CAESAR", "Proper Name"),
    ("HELEN KELLER", "Proper Name"),

    # Proper Place
    ("NIAGARA FALLS", "Proper Place"),
    ("TIMES SQUARE", "Proper Place"),
    ("GRAND CANYON", "Proper Place"),
    ("EIFFEL TOWER", "Proper Place"),
    ("CENTRAL PARK", "Proper Place"),
    ("GOLDEN GATE BRIDGE", "Proper Place"),
    ("MOUNT RUSHMORE", "Proper Place"),
    ("STATUE OF LIBERTY", "Proper Place"),
    ("EMPIRE STATE BUILDING", "Proper Place"),
    ("YELLOWSTONE NATIONAL PARK", "Proper Place"),
    ("VENICE BEACH", "Proper Place"),
    ("BOURBON STREET", "Proper Place"),
    ("BUCKINGHAM PALACE", "Proper Place"),
    ("GREAT BARRIER REEF", "Proper Place"),
    ("SAHARA DESERT", "Proper Place"),
    ("MOUNT EVEREST", "Proper Place"),
    ("AMAZON RAIN FOREST", "Proper Place"),
    ("STONEHENGE", "Proper Place"),
    ("MACHU PICCHU", "Proper Place"),
    ("SYDNEY OPERA HOUSE", "Proper Place"),
    ("COLOSSEUM", "Proper Place"),
    ("TAJ MAHAL", "Proper Place"),
    ("GREAT WALL OF CHINA", "Proper Place"),
    ("ANGEL FALLS", "Proper Place"),
    ("VICTORIA FALLS", "Proper Place"),

    # Place
    ("POND IN THE PARK", "Place"),
    ("CORNER COFFEE SHOP", "Place"),
    ("END OF THE DRIVEWAY", "Place"),
    ("BACK OF THE CLOSET", "Place"),
    ("TOP OF THE STAIRS", "Place"),
    ("UNDER THE BRIDGE", "Place"),
    ("BEHIND THE WATERFALL", "Place"),
    ("MIDDLE OF NOWHERE", "Place"),
    ("BOTTOM OF THE OCEAN", "Place"),
    ("EDGE OF THE CLIFF", "Place"),
    ("OLD FISHING DOCK", "Place"),
    ("BACK CORNER BOOTH", "Place"),
    ("ABANDONED TRAIN STATION", "Place"),
    ("ROOFTOP GARDEN", "Place"),
    ("HIDDEN CLEARING IN THE WOODS", "Place"),
    ("LITTLE LEAGUE BASEBALL FIELD", "Place"),
    ("TOWN SQUARE FOUNTAIN", "Place"),
    ("NEIGHBORHOOD SWIMMING HOLE", "Place"),
    ("DUSTY COUNTRY ROAD", "Place"),
    ("END OF THE RAINBOW", "Place"),
    ("BOTTOM OF THE GARDEN", "Place"),
    ("OLD COVERED BRIDGE", "Place"),
    ("MIDNIGHT DINER", "Place"),
    ("TOP OF THE FERRIS WHEEL", "Place"),
    ("BACK ROW OF THE MOVIE THEATER", "Place"),

    # Phrase
    ("ACTIONS SPEAK LOUDER THAN WORDS", "Phrase"),
    ("EVERY CLOUD HAS A SILVER LINING", "Phrase"),
    ("THE EARLY BIRD CATCHES THE WORM", "Phrase"),
    ("BETTER LATE THAN NEVER", "Phrase"),
    ("BITE THE BULLET", "Phrase"),
    ("HIT THE NAIL ON THE HEAD", "Phrase"),
    ("BREAK A LEG", "Phrase"),
    ("SPILL THE BEANS", "Phrase"),
    ("UNDER THE WEATHER", "Phrase"),
    ("ONCE IN A BLUE MOON", "Phrase"),
    ("COST AN ARM AND A LEG", "Phrase"),
    ("LET THE CAT OUT OF THE BAG", "Phrase"),
    ("BURNING THE MIDNIGHT OIL", "Phrase"),
    ("JUMP ON THE BANDWAGON", "Phrase"),
    ("THE BALL IS IN YOUR COURT", "Phrase"),
    ("BARKING UP THE WRONG TREE", "Phrase"),
    ("BEAT AROUND THE BUSH", "Phrase"),
    ("BITE OFF MORE THAN YOU CAN CHEW", "Phrase"),
    ("CAUGHT BETWEEN A ROCK AND A HARD PLACE", "Phrase"),
    ("DONT COUNT YOUR CHICKENS", "Phrase"),
    ("EVERY DOG HAS ITS DAY", "Phrase"),
    ("KILL TWO BIRDS WITH ONE STONE", "Phrase"),
    ("THE BEST OF BOTH WORLDS", "Phrase"),
    ("WHEN PIGS FLY", "Phrase"),
    ("YOU CANT JUDGE A BOOK BY ITS COVER", "Phrase"),

    # Before & After
    ("PEANUT BUTTER CUP CAKE", "Before & After"),
    ("HOT DOG HOUSE MUSIC", "Before & After"),
    ("ROCK BAND WAGON", "Before & After"),
    ("GOLD FISH TANK TOP", "Before & After"),
    ("BLACK BIRD HOUSE", "Before & After"),
    ("SNOW BALL PARK", "Before & After"),
    ("SUN FLOWER POWER", "Before & After"),
    ("FIRE TRUCK STOP", "Before & After"),
    ("RAIN BOW TIE", "Before & After"),
    ("MOON LIGHT HOUSE", "Before & After"),
    ("BUTTER CUP CAKE WALK", "Before & After"),
    ("SUPER MAN HOLE COVER", "Before & After"),
    ("SPEED BOAT HOUSE KEEPER", "Before & After"),
    ("BOOK WORM HOLE", "Before & After"),
    ("SAND CASTLE ROCK", "Before & After"),
    ("BASE BALL ROOM DANCE", "Before & After"),
    ("EYE BALL PARK BENCH", "Before & After"),
    ("FIRE PLACE HOLDER", "Before & After"),
    ("GRASS HOPPER SCOTCH", "Before & After"),
    ("HEAD BAND STAND", "Before & After"),
    ("IRON MAN HOLE", "Before & After"),
    ("KEY BOARD GAME", "Before & After"),
    ("LAMP SHADE TREE", "Before & After"),
    ("NIGHT CLUB HOUSE", "Before & After"),
    ("OVER COAT RACK", "Before & After"),

    # Food & Drink
    ("MACARONI AND CHEESE", "Food & Drink"),
    ("CHICKEN PARMESAN", "Food & Drink"),
    ("STRAWBERRY SHORTCAKE", "Food & Drink"),
    ("FRENCH ONION SOUP", "Food & Drink"),
    ("EGGS BENEDICT", "Food & Drink"),
    ("BANANA SPLIT", "Food & Drink"),
    ("GRILLED CHEESE SANDWICH", "Food & Drink"),
    ("CHOCOLATE LAVA CAKE", "Food & Drink"),
    ("CAESAR SALAD", "Food & Drink"),
    ("PEANUT BUTTER AND JELLY", "Food & Drink"),
    ("BEEF WELLINGTON", "Food & Drink"),
    ("FISH AND CHIPS", "Food & Drink"),
    ("LOBSTER BISQUE", "Food & Drink"),
    ("MONTE CRISTO SANDWICH", "Food & Drink"),
    ("BAKED ALASKA", "Food & Drink"),
    ("CHICKEN TIKKA MASALA", "Food & Drink"),
    ("CRÈME BRÛLÉE", "Food & Drink"),
    ("SHRIMP SCAMPI", "Food & Drink"),
    ("BUFFALO CHICKEN WINGS", "Food & Drink"),
    ("SWEET POTATO PIE", "Food & Drink"),
    ("PULLED PORK SANDWICH", "Food & Drink"),
    ("MOZZARELLA STICKS", "Food & Drink"),
    ("BLUEBERRY PANCAKES", "Food & Drink"),
    ("CLAM CHOWDER", "Food & Drink"),
    ("AVOCADO TOAST", "Food & Drink"),

    # Event
    ("SUPER BOWL SUNDAY", "Event"),
    ("NEW YEARS EVE PARTY", "Event"),
    ("FOURTH OF JULY FIREWORKS", "Event"),
    ("THANKSGIVING DINNER", "Event"),
    ("HALLOWEEN COSTUME PARTY", "Event"),
    ("MARDI GRAS PARADE", "Event"),
    ("ACADEMY AWARDS CEREMONY", "Event"),
    ("WORLD CUP FINAL", "Event"),
    ("SOLAR ECLIPSE", "Event"),
    ("OLYMPIC OPENING CEREMONY", "Event"),
    ("ROYAL WEDDING", "Event"),
    ("MIDNIGHT COUNTDOWN", "Event"),
    ("COUNTY FAIR", "Event"),
    ("HIGH SCHOOL REUNION", "Event"),
    ("GROUNDHOG DAY", "Event"),
    ("SPRING CLEANING", "Event"),
    ("NEIGHBORHOOD BLOCK PARTY", "Event"),
    ("RETIREMENT PARTY", "Event"),
    ("BACHELOR AUCTION", "Event"),
    ("SCIENCE FAIR", "Event"),
    ("TALENT SHOW", "Event"),
    ("SPELLING BEE", "Event"),
    ("CHILI COOK OFF", "Event"),
    ("SURPRISE BIRTHDAY PARTY", "Event"),
    ("GRADUATION CEREMONY", "Event"),

    # Around the House
    ("KITCHEN SINK", "Around the House"),
    ("LIVING ROOM COUCH", "Around the House"),
    ("MASTER BEDROOM", "Around the House"),
    ("WALK IN CLOSET", "Around the House"),
    ("BATHROOM MIRROR", "Around the House"),
    ("FRONT PORCH SWING", "Around the House"),
    ("GARAGE DOOR OPENER", "Around the House"),
    ("BASEMENT STAIRS", "Around the House"),
    ("BACKYARD PATIO", "Around the House"),
    ("DINING ROOM TABLE", "Around the House"),
    ("JUNK DRAWER", "Around the House"),
    ("MEDICINE CABINET", "Around the House"),
    ("MUDROOM BENCH", "Around the House"),
    ("ATTIC HATCH", "Around the House"),
    ("LAUNDRY CHUTE", "Around the House"),
    ("WINDOW SEAT", "Around the House"),
    ("BREAKFAST NOOK", "Around the House"),
    ("COAT CLOSET", "Around the House"),
    ("UTILITY ROOM", "Around the House"),
    ("BACK DOOR STEPS", "Around the House"),
    ("FIREPLACE MANTLE", "Around the House"),
    ("PANTRY SHELF", "Around the House"),
    ("LINEN CLOSET", "Around the House"),
    ("SUNROOM", "Around the House"),
    ("CRAWL SPACE", "Around the House"),

    # What Are You Doing?
    ("TAKING A BUBBLE BATH", "What Are You Doing?"),
    ("WALKING THE DOG", "What Are You Doing?"),
    ("MAKING BREAKFAST", "What Are You Doing?"),
    ("WATCHING THE SUNSET", "What Are You Doing?"),
    ("READING A GOOD BOOK", "What Are You Doing?"),
    ("PLAYING VIDEO GAMES", "What Are You Doing?"),
    ("BAKING CHOCOLATE CHIP COOKIES", "What Are You Doing?"),
    ("TAKING OUT THE TRASH", "What Are You Doing?"),
    ("MOWING THE LAWN", "What Are You Doing?"),
    ("PAINTING THE BEDROOM", "What Are You Doing?"),
    ("LEARNING TO PLAY GUITAR", "What Are You Doing?"),
    ("RUNNING A MARATHON", "What Are You Doing?"),
    ("FEEDING THE DUCKS", "What Are You Doing?"),
    ("BUILDING A SANDCASTLE", "What Are You Doing?"),
    ("CLEANING THE GARAGE", "What Are You Doing?"),
    ("TEACHING THE DOG A NEW TRICK", "What Are You Doing?"),
    ("WATCHING PAINT DRY", "What Are You Doing?"),
    ("COUNTING SHEEP", "What Are You Doing?"),
    ("CHASING YOUR TAIL", "What Are You Doing?"),
    ("KNITTING A SWEATER", "What Are You Doing?"),
    ("STARGAZING IN THE BACKYARD", "What Are You Doing?"),
    ("SORTING THE RECYCLING", "What Are You Doing?"),
    ("REORGANIZING THE PANTRY", "What Are You Doing?"),
    ("PRESSING WILDFLOWERS", "What Are You Doing?"),
    ("WRITING IN A JOURNAL", "What Are You Doing?"),

    # Occupation
    ("AIR TRAFFIC CONTROLLER", "Occupation"),
    ("SUBMARINE COMMANDER", "Occupation"),
    ("FORENSIC ACCOUNTANT", "Occupation"),
    ("WILDLIFE PHOTOGRAPHER", "Occupation"),
    ("ROLLER COASTER DESIGNER", "Occupation"),
    ("SPEECH PATHOLOGIST", "Occupation"),
    ("MARINE BIOLOGIST", "Occupation"),
    ("STORM CHASER", "Occupation"),
    ("TATTOO ARTIST", "Occupation"),
    ("FOOD CRITIC", "Occupation"),
    ("STUNT DOUBLE", "Occupation"),
    ("CHESS GRANDMASTER", "Occupation"),
    ("WINE SOMMELIER", "Occupation"),
    ("VOLCANOLOGIST", "Occupation"),
    ("SPECIAL EFFECTS ARTIST", "Occupation"),
    ("CROSSWORD PUZZLE CONSTRUCTOR", "Occupation"),
    ("PROFESSIONAL ORGANIZER", "Occupation"),
    ("DEEP SEA DIVER", "Occupation"),
    ("DOG SLED RACER", "Occupation"),
    ("SPORTS ANNOUNCER", "Occupation"),
    ("LIGHTHOUSE KEEPER", "Occupation"),
    ("PRIVATE INVESTIGATOR", "Occupation"),
    ("HAND MODEL", "Occupation"),
    ("VOICE ACTOR", "Occupation"),
    ("ETHICAL HACKER", "Occupation"),
]