PUZZLES = [

    # -------------------------------------------------------------------------
    # Around the House
    # -------------------------------------------------------------------------

    ("ATTIC HATCH", "Around the House"),
    ("BACK DOOR STEPS", "Around the House"),
    ("BACK FENCE", "Around the House"),
    ("BACK OF THE FRIDGE", "Around the House"),
    ("BASEMENT STAIRS", "Around the House"),
    ("BASEMENT STORAGE ROOM", "Around the House"),
    ("BATH TUB", "Around the House"),
    ("BATHROOM EXHAUST FAN", "Around the House"),
    ("BATHROOM MIRROR", "Around the House"),
    ("BEHIND THE COUCH", "Around the House"),
    ("BOTTOM OF THE STAIRS", "Around the House"),
    ("BREAKFAST NOOK", "Around the House"),
    ("BROKEN PORCH RAILING", "Around the House"),
    ("BUILT IN BOOKCASE", "Around the House"),
    ("CELLAR DOOR", "Around the House"),
    ("COAT CLOSET", "Around the House"),
    ("COAT HOOK", "Around the House"),
    ("COBWEBS IN THE CORNER OF THE GARAGE", "Around the House"),
    ("CONVERTED GARAGE STUDIO", "Around the House"),
    ("CRACKED TILE BEHIND THE STOVE", "Around the House"),
    ("CRAWL SPACE", "Around the House"),
    ("DINING ROOM TABLE", "Around the House"),
    ("FIREPLACE MANTLE", "Around the House"),
    ("FLICKERING PORCH LIGHT FIXTURE", "Around the House"),
    ("FRONT HALL MIRROR", "Around the House"),
    ("FRONT PORCH SWING", "Around the House"),
    ("FRONT STOOP", "Around the House"),
    ("GARAGE DOOR OPENER", "Around the House"),
    ("GARAGE WORKBENCH", "Around the House"),
    ("GARDEN GATE", "Around the House"),
    ("GUEST ROOM BED", "Around the House"),
    ("JUNK DRAWER", "Around the House"),
    ("KITCHEN ISLAND COUNTER", "Around the House"),
    ("KITCHEN SINK", "Around the House"),
    ("LAUNDRY CHUTE", "Around the House"),
    ("LAUNDRY ROOM FLOOR", "Around the House"),
    ("LEAKY FAUCET IN THE BASEMENT SINK", "Around the House"),
    ("LINEN CLOSET", "Around the House"),
    ("LIVING ROOM COUCH", "Around the House"),
    ("MAIL SLOT", "Around the House"),
    ("MASTER BATH SOAKING TUB", "Around the House"),
    ("MASTER BEDROOM", "Around the House"),
    ("MEDICINE CABINET", "Around the House"),
    ("MUDROOM BENCH", "Around the House"),
    ("MUDROOM COAT RACK", "Around the House"),
    ("OUTDOOR SHOWER STALL", "Around the House"),
    ("OVERGROWN WALKWAY TO THE SHED", "Around the House"),
    ("PANTRY SHELF", "Around the House"),
    ("PEELING WALLPAPER IN THE POWDER ROOM", "Around the House"),
    ("RAIN GUTTER", "Around the House"),
    ("READING NOOK CUSHION", "Around the House"),
    ("SCREEN DOOR", "Around the House"),
    ("SECOND FLOOR LANDING", "Around the House"),
    ("SHED DOOR", "Around the House"),
    ("SIDE GATE", "Around the House"),
    ("SMOKE ALARM BATTERY", "Around the House"),
    ("SPICE CABINET", "Around the House"),
    ("SQUEAKY FLOORBOARD IN THE HALLWAY", "Around the House"),
    ("STORM DOOR", "Around the House"),
    ("SUNROOM", "Around the House"),
    ("THE BACK BEDROOM", "Around the House"),
    ("THE BACK DOOR", "Around the House"),
    ("THE BACK PORCH", "Around the House"),
    ("THE BACK STAIRCASE", "Around the House"),
    ("THE CORKBOARD", "Around the House"),
    ("THE FRONT STEP", "Around the House"),
    ("THE GARDEN SHED", "Around the House"),
    ("THE HALL CLOSET", "Around the House"),
    ("THE HOT TUB", "Around the House"),
    ("THE JUNK ROOM", "Around the House"),
    ("THE RECYCLING BIN", "Around the House"),
    ("THE SOCK DRAWER", "Around the House"),
    ("THE STORM CELLAR", "Around the House"),
    ("TOOL SHED", "Around the House"),
    ("TOP OF THE FRIDGE", "Around the House"),
    ("UNDER STAIR STORAGE", "Around the House"),
    ("UNDER THE BED", "Around the House"),
    ("UNDER THE DECK", "Around the House"),
    ("UNDER THE PORCH", "Around the House"),
    ("UNDER THE SINK", "Around the House"),
    ("UTILITY ROOM", "Around the House"),
    ("WALK IN CLOSET", "Around the House"),
    ("WATER STAIN ON THE BEDROOM CEILING", "Around the House"),
    ("WINDOW LEDGE", "Around the House"),
    ("WINDOW SEAT", "Around the House"),
    ("WOOD BURNING STOVE", "Around the House"),

    # -------------------------------------------------------------------------
    # Event
    # -------------------------------------------------------------------------

    ("ACADEMY AWARDS CEREMONY", "Event"),
    ("ANTIQUE ROAD SHOW", "Event"),
    ("AWARDS BANQUET", "Event"),
    ("BACHELOR AUCTION", "Event"),
    ("BAKE SALE", "Event"),
    ("BARN DANCE", "Event"),
    ("BLOOD DRIVE", "Event"),
    ("BOAT PARADE", "Event"),
    ("BOOK FAIR", "Event"),
    ("CAR SHOW", "Event"),
    ("CELEBRITY CHEF COOKOFF", "Event"),
    ("CHAMPIONSHIP BOXING MATCH", "Event"),
    ("CHARITY AUCTION", "Event"),
    ("CHILI COOK OFF", "Event"),
    ("CHORAL CONCERT", "Event"),
    ("CHRISTENING CEREMONY", "Event"),
    ("CHRISTMAS TREE LIGHTING", "Event"),
    ("CINCO DE MAYO CELEBRATION", "Event"),
    ("COLONIAL REENACTMENT FESTIVAL", "Event"),
    ("COMPETITIVE BARBECUE CHAMPIONSHIP", "Event"),
    ("COMPETITIVE ROBOTICS TOURNAMENT", "Event"),
    ("CORPORATE BOARD MEETING", "Event"),
    ("COUNTY FAIR", "Event"),
    ("CRAFT BEER FESTIVAL", "Event"),
    ("DEMOLITION DERBY", "Event"),
    ("DIPLOMATIC SUMMIT", "Event"),
    ("DOG SHOW", "Event"),
    ("FILM FESTIVAL OPENING NIGHT", "Event"),
    ("FIREWORKS GRAND FINALE", "Event"),
    ("FISH FRY", "Event"),
    ("FIRST DAY OF SCHOOL", "Event"),
    ("FLOWER SHOW", "Event"),
    ("FOOD DRIVE", "Event"),
    ("FOURTH OF JULY FIREWORKS", "Event"),
    ("FUNDRAISER GALA", "Event"),
    ("GAME NIGHT", "Event"),
    ("GRADUATION CEREMONY", "Event"),
    ("GROUNDBREAKING CEREMONY", "Event"),
    ("GROUNDHOG DAY", "Event"),
    ("HALF TIME SHOW", "Event"),
    ("HALLOWEEN COSTUME PARTY", "Event"),
    ("HARVEST MOON FESTIVAL", "Event"),
    ("HIGH SCHOOL REUNION", "Event"),
    ("HOMECOMING PARADE", "Event"),
    ("HORSE SHOW", "Event"),
    ("INTERNATIONAL BALLOON FIESTA", "Event"),
    ("INTERNATIONAL CHESS TOURNAMENT", "Event"),
    ("LAST DAY OF SCHOOL", "Event"),
    ("MARDI GRAS PARADE", "Event"),
    ("MARATHON FINISH LINE", "Event"),
    ("MEDIEVAL JOUSTING TOURNAMENT", "Event"),
    ("MEMORIAL DAY COOKOUT", "Event"),
    ("MIDNIGHT COUNTDOWN", "Event"),
    ("MOCK TRIAL", "Event"),
    ("MOON LANDING", "Event"),
    ("NATIONAL SPELLING CHAMPIONSHIP", "Event"),
    ("NEIGHBORHOOD BLOCK PARTY", "Event"),
    ("NEIGHBORHOOD GARAGE SALE", "Event"),
    ("NEW YEARS EVE PARTY", "Event"),
    ("OLYMPIC OPENING CEREMONY", "Event"),
    ("OPEN MIC NIGHT", "Event"),
    ("PANCAKE BREAKFAST FUNDRAISER", "Event"),
    ("PEP RALLY", "Event"),
    ("PIE EATING CONTEST", "Event"),
    ("PIANO RECITAL", "Event"),
    ("POLAR BEAR PLUNGE", "Event"),
    ("POT LUCK DINNER", "Event"),
    ("PRESIDENTIAL INAUGURATION", "Event"),
    ("PROFESSIONAL BULL RIDING CHAMPIONSHIP", "Event"),
    ("PROFESSIONAL GOLF TOURNAMENT PLAYOFF", "Event"),
    ("PROFESSIONAL WRESTLING GRUDGE MATCH", "Event"),
    ("PROM NIGHT", "Event"),
    ("RETIREMENT PARTY", "Event"),
    ("RIBBON CUTTING CEREMONY", "Event"),
    ("ROYAL GUARD CHANGING CEREMONY", "Event"),
    ("ROYAL WEDDING", "Event"),
    ("SCHOOL PLAY", "Event"),
    ("SCIENCE FAIR", "Event"),
    ("SOCK HOP", "Event"),
    ("SOLAR ECLIPSE", "Event"),
    ("SPELLING BEE", "Event"),
    ("SPRING CLEANING", "Event"),
    ("STATE FAIR OPENING DAY", "Event"),
    ("SUMMER SOLSTICE CELEBRATION", "Event"),
    ("SUPER BOWL SUNDAY", "Event"),
    ("SURPRISE BIRTHDAY PARTY", "Event"),
    ("SYNCHRONIZED DIVING CHAMPIONSHIP", "Event"),
    ("SYNCHRONIZED SWIMMING GALA", "Event"),
    ("TALENT SHOW", "Event"),
    ("THANKSGIVING DINNER", "Event"),
    ("WORLD CUP FINAL", "Event"),
    ("WORLD SERIES GAME SEVEN", "Event"),

    # -------------------------------------------------------------------------
    # Food & Drink
    # -------------------------------------------------------------------------

    ("ANGEL FOOD CAKE", "Food & Drink"),
    ("APPLE CIDER", "Food & Drink"),
    ("AVOCADO TOAST", "Food & Drink"),
    ("BAKED ALASKA", "Food & Drink"),
    ("BANANA BREAD", "Food & Drink"),
    ("BANANA SPLIT", "Food & Drink"),
    ("BANGERS AND MASH", "Food & Drink"),
    ("BEEF BOURGUIGNON", "Food & Drink"),
    ("BEEF STEAK", "Food & Drink"),
    ("BEEF STROGANOFF", "Food & Drink"),
    ("BISCUITS AND GRAVY", "Food & Drink"),
    ("BLACK BEAN SOUP", "Food & Drink"),
    ("BLACKENED SWORDFISH WITH MANGO SALSA", "Food & Drink"),
    ("BLUEBERRY PANCAKES", "Food & Drink"),
    ("BOURBON BREAD PUDDING", "Food & Drink"),
    ("BREAD ROLL", "Food & Drink"),
    ("BUFFALO CHICKEN WINGS", "Food & Drink"),
    ("BUTTERSCOTCH PUDDING", "Food & Drink"),
    ("CAESAR SALAD", "Food & Drink"),
    ("CARROT GINGER SOUP", "Food & Drink"),
    ("CHARRED BRUSSELS SPROUTS", "Food & Drink"),
    ("CHEESE STEAK", "Food & Drink"),
    ("CHICKEN MARSALA", "Food & Drink"),
    ("CHICKEN NOODLE SOUP", "Food & Drink"),
    ("CHICKEN PARMESAN", "Food & Drink"),
    ("CHICKEN TIKKA MASALA", "Food & Drink"),
    ("CHILI CHEESE FRIES", "Food & Drink"),
    ("CLAM CHOWDER", "Food & Drink"),
    ("CLUB SANDWICH", "Food & Drink"),
    ("COBB SALAD", "Food & Drink"),
    ("CORN BREAD", "Food & Drink"),
    ("CORN DOG", "Food & Drink"),
    ("CRAB CAKE", "Food & Drink"),
    ("CREAM PUFF", "Food & Drink"),
    ("CREME BRULEE", "Food & Drink"),
    ("DUCK CONFIT WITH LENTILS", "Food & Drink"),
    ("EGG ROLL", "Food & Drink"),
    ("EGGS BENEDICT", "Food & Drink"),
    ("FISH AND CHIPS", "Food & Drink"),
    ("FISH TACO", "Food & Drink"),
    ("FRENCH ONION SOUP", "Food & Drink"),
    ("FRENCH TOAST", "Food & Drink"),
    ("GERMAN CHOCOLATE CAKE", "Food & Drink"),
    ("GREEN TEA", "Food & Drink"),
    ("GRILLED CHEESE SANDWICH", "Food & Drink"),
    ("HAM STEAK", "Food & Drink"),
    ("HOLLANDAISE SAUCE", "Food & Drink"),
    ("HOT DOG", "Food & Drink"),
    ("ICED TEA", "Food & Drink"),
    ("LAMB CHOP", "Food & Drink"),
    ("LOBSTER BISQUE", "Food & Drink"),
    ("MACARONI AND CHEESE", "Food & Drink"),
    ("MAPLE BACON DONUT", "Food & Drink"),
    ("MEAT LOAF", "Food & Drink"),
    ("MEAT PIE", "Food & Drink"),
    ("MONTE CRISTO SANDWICH", "Food & Drink"),
    ("MOZZARELLA STICKS", "Food & Drink"),
    ("ONION RING", "Food & Drink"),
    ("PEACH COBBLER", "Food & Drink"),
    ("PEACH PIE", "Food & Drink"),
    ("PEANUT BUTTER AND JELLY", "Food & Drink"),
    ("PEKING DUCK", "Food & Drink"),
    ("PENNE ARRABBIATA", "Food & Drink"),
    ("PICKLED WATERMELON RIND", "Food & Drink"),
    ("PITA BREAD", "Food & Drink"),
    ("POACHED PEAR IN RED WINE", "Food & Drink"),
    ("POTATO LEEK SOUP", "Food & Drink"),
    ("POUND CAKE", "Food & Drink"),
    ("PRIME RIB ROAST", "Food & Drink"),
    ("PROSCIUTTO WRAPPED MELON", "Food & Drink"),
    ("PULLED PORK SANDWICH", "Food & Drink"),
    ("RATATOUILLE", "Food & Drink"),
    ("RICE CAKE", "Food & Drink"),
    ("SAFFRON RISOTTO WITH SCALLOPS", "Food & Drink"),
    ("SHEPHERDS PIE", "Food & Drink"),
    ("SHRIMP SCAMPI", "Food & Drink"),
    ("SLOW ROASTED PORK BELLY", "Food & Drink"),
    ("SMOKED GOUDA GRILLED CHEESE", "Food & Drink"),
    ("SMOKED PAPRIKA CHICKEN THIGHS", "Food & Drink"),
    ("SOFT PRETZEL", "Food & Drink"),
    ("SPAGHETTI AND MEATBALLS", "Food & Drink"),
    ("SPLIT PEA SOUP", "Food & Drink"),
    ("STRAWBERRY SHORTCAKE", "Food & Drink"),
    ("SWEET POTATO PIE", "Food & Drink"),
    ("SZECHUAN PEPPERCORN BEEF", "Food & Drink"),
    ("TOMATO BISQUE", "Food & Drink"),
    ("TUNA NOODLE CASSEROLE", "Food & Drink"),
    ("WALNUT BROWNIE", "Food & Drink"),

    # -------------------------------------------------------------------------
    # Occupation
    # -------------------------------------------------------------------------

    ("AIR TRAFFIC CONTROLLER", "Occupation"),
    ("ANIMAL CONTROL OFFICER", "Occupation"),
    ("AVALANCHE FORECASTER", "Occupation"),
    ("BIKE MESSENGER", "Occupation"),
    ("BOMB DISPOSAL TECHNICIAN", "Occupation"),
    ("BORDER PATROL AGENT", "Occupation"),
    ("BUILDING INSPECTOR", "Occupation"),
    ("CAVE TOUR GUIDE", "Occupation"),
    ("CHESS GRANDMASTER", "Occupation"),
    ("CHILDRENS BOOK ILLUSTRATOR", "Occupation"),
    ("COMPETITIVE BALLROOM DANCE JUDGE", "Occupation"),
    ("COMPETITIVE EATING CHAMPION", "Occupation"),
    ("COMPETITIVE SCRABBLE PLAYER", "Occupation"),
    ("CONFLICT MEDIATOR", "Occupation"),
    ("COURT REPORTER", "Occupation"),
    ("CRIME SCENE CLEANER", "Occupation"),
    ("CROP DUSTER PILOT", "Occupation"),
    ("CROSSWORD PUZZLE CONSTRUCTOR", "Occupation"),
    ("DEEP SEA DIVER", "Occupation"),
    ("DEMOLITION DERBY DRIVER", "Occupation"),
    ("DOG SLED RACER", "Occupation"),
    ("ETHICAL HACKER", "Occupation"),
    ("FIRE LOOKOUT", "Occupation"),
    ("FOOD CRITIC", "Occupation"),
    ("FORENSIC ACCOUNTANT", "Occupation"),
    ("FORENSIC ENTOMOLOGIST", "Occupation"),
    ("FORENSIC SKETCH ARTIST", "Occupation"),
    ("FUNERAL HOME DIRECTOR", "Occupation"),
    ("GOLF CADDIE", "Occupation"),
    ("GRAFFITI REMOVAL SPECIALIST", "Occupation"),
    ("HALL MONITOR", "Occupation"),
    ("HAND MODEL", "Occupation"),
    ("HARBOR MASTER", "Occupation"),
    ("HORSE TRAINER", "Occupation"),
    ("LIGHTHOUSE KEEPER", "Occupation"),
    ("MAIL CARRIER", "Occupation"),
    ("MARINE BIOLOGIST", "Occupation"),
    ("MOUNTAIN RESCUE COORDINATOR", "Occupation"),
    ("NIGHT WATCHMAN", "Occupation"),
    ("NUCLEAR SUBMARINE COOK", "Occupation"),
    ("PARK RANGER", "Occupation"),
    ("POLITICAL CARTOONIST", "Occupation"),
    ("POOL LIFEGUARD", "Occupation"),
    ("PRIVATE INVESTIGATOR", "Occupation"),
    ("PROFESSIONAL BRIDESMAID", "Occupation"),
    ("PROFESSIONAL CUDDLER", "Occupation"),
    ("PROFESSIONAL FOLEY ARTIST", "Occupation"),
    ("PROFESSIONAL GENEALOGIST", "Occupation"),
    ("PROFESSIONAL LINE SITTER", "Occupation"),
    ("PROFESSIONAL MOURNER", "Occupation"),
    ("PROFESSIONAL ORGANIZER", "Occupation"),
    ("PROFESSIONAL POKER PLAYER", "Occupation"),
    ("PROFESSIONAL WHISTLEBLOWER", "Occupation"),
    ("ROLLER COASTER DESIGNER", "Occupation"),
    ("ROLLER DERBY COACH", "Occupation"),
    ("SCHOOL BUS DRIVER", "Occupation"),
    ("SHIP CAPTAIN", "Occupation"),
    ("SIGN LANGUAGE INTERPRETER", "Occupation"),
    ("SIGN PAINTER", "Occupation"),
    ("SLEEP TECHNOLOGIST", "Occupation"),
    ("SMOKE JUMPER", "Occupation"),
    ("SPACE DEBRIS TRACKER", "Occupation"),
    ("SPECIAL EFFECTS ARTIST", "Occupation"),
    ("SPEECH PATHOLOGIST", "Occupation"),
    ("SPORTS ANNOUNCER", "Occupation"),
    ("SPORTS PHOTOGRAPHER", "Occupation"),
    ("STORM CHASER", "Occupation"),
    ("STREET PERFORMER", "Occupation"),
    ("STUNT DOUBLE", "Occupation"),
    ("SUBMARINE COMMANDER", "Occupation"),
    ("TATTOO ARTIST", "Occupation"),
    ("THEATRICAL FIGHT CHOREOGRAPHER", "Occupation"),
    ("TOLL BOOTH OPERATOR", "Occupation"),
    ("TRAIN CONDUCTOR", "Occupation"),
    ("TREE SURGEON", "Occupation"),
    ("UNDERWATER WELDER", "Occupation"),
    ("VOICE ACTOR", "Occupation"),
    ("WILDLIFE PHOTOGRAPHER", "Occupation"),
    ("WINE SOMMELIER", "Occupation"),
    ("VOLCANOLOGIST", "Occupation"),

    # -------------------------------------------------------------------------
    # Phrase
    # -------------------------------------------------------------------------

    ("A BLESSING IN DISGUISE", "Phrase"),
    ("A PENNY FOR YOUR THOUGHTS", "Phrase"),
    ("ACTIONS SPEAK LOUDER THAN WORDS", "Phrase"),
    ("ADD FUEL TO THE FIRE", "Phrase"),
    ("BACK TO SQUARE ONE", "Phrase"),
    ("BARKING UP THE WRONG TREE", "Phrase"),
    ("BEAT AROUND THE BUSH", "Phrase"),
    ("BEATING A DEAD HORSE", "Phrase"),
    ("BETTER LATE THAN NEVER", "Phrase"),
    ("BITE OFF MORE THAN YOU CAN CHEW", "Phrase"),
    ("BITE THE BULLET", "Phrase"),
    ("BITE THE DUST", "Phrase"),
    ("BITE THE HAND THAT FEEDS YOU", "Phrase"),
    ("BLOOD IS THICKER THAN WATER", "Phrase"),
    ("BREAK A LEG", "Phrase"),
    ("BURN THE MIDNIGHT OIL", "Phrase"),
    ("BURNING BRIDGES", "Phrase"),
    ("BURNING THE CANDLE AT BOTH ENDS", "Phrase"),
    ("CALL IT A DAY", "Phrase"),
    ("CANT SEE THE FOREST FOR THE TREES", "Phrase"),
    ("CAUGHT BETWEEN A ROCK AND A HARD PLACE", "Phrase"),
    ("CAUGHT WITH YOUR HAND IN THE COOKIE JAR", "Phrase"),
    ("COMPARING APPLES TO ORANGES", "Phrase"),
    ("COST AN ARM AND A LEG", "Phrase"),
    ("COVER ALL YOUR BASES", "Phrase"),
    ("CROSS THAT BRIDGE WHEN YOU COME TO IT", "Phrase"),
    ("CUT TO THE CHASE", "Phrase"),
    ("DANCING AROUND THE SUBJECT", "Phrase"),
    ("DONT COUNT YOUR CHICKENS", "Phrase"),
    ("DONT LOOK A GIFT HORSE IN THE MOUTH", "Phrase"),
    ("DONT THROW THE BABY OUT WITH THE BATHWATER", "Phrase"),
    ("EVERY CLOUD HAS A SILVER LINING", "Phrase"),
    ("EVERY DOG HAS ITS DAY", "Phrase"),
    ("GIVE CREDIT WHERE CREDIT IS DUE", "Phrase"),
    ("GIVE IT A SHOT", "Phrase"),
    ("GO BACK TO THE DRAWING BOARD", "Phrase"),
    ("HAVE YOUR CAKE AND EAT IT TOO", "Phrase"),
    ("HIT THE NAIL ON THE HEAD", "Phrase"),
    ("HIT THE ROAD", "Phrase"),
    ("HIT THE SACK", "Phrase"),
    ("IN HOT WATER", "Phrase"),
    ("IT TAKES TWO TO TANGO", "Phrase"),
    ("JUMP FROM THE FRYING PAN INTO THE FIRE", "Phrase"),
    ("JUMP ON THE BANDWAGON", "Phrase"),
    ("KILL TWO BIRDS WITH ONE STONE", "Phrase"),
    ("LET SLEEPING DOGS LIE", "Phrase"),
    ("LET THE CAT OUT OF THE BAG", "Phrase"),
    ("LIKE FINDING A NEEDLE IN A HAYSTACK", "Phrase"),
    ("MAKING A MOUNTAIN OUT OF A MOLEHILL", "Phrase"),
    ("MISS THE BOAT", "Phrase"),
    ("OFF THE TOP OF MY HEAD", "Phrase"),
    ("ON THE FENCE", "Phrase"),
    ("ON THIN ICE", "Phrase"),
    ("ONCE IN A BLUE MOON", "Phrase"),
    ("PIECE OF CAKE", "Phrase"),
    ("PULL OUT ALL THE STOPS", "Phrase"),
    ("PULL SOMEONES LEG", "Phrase"),
    ("PULLING THE WOOL OVER SOMEONES EYES", "Phrase"),
    ("PUT A SOCK IN IT", "Phrase"),
    ("PUT ALL YOUR EGGS IN ONE BASKET", "Phrase"),
    ("ROBBING PETER TO PAY PAUL", "Phrase"),
    ("SHOOTING THE MESSENGER", "Phrase"),
    ("SPEAK OF THE DEVIL", "Phrase"),
    ("SPILL THE BEANS", "Phrase"),
    ("SQUEEZING BLOOD FROM A TURNIP", "Phrase"),
    ("STEAL SOMEONES THUNDER", "Phrase"),
    ("STRIKE WHILE THE IRON IS HOT", "Phrase"),
    ("TAKE THE BULL BY THE HORNS", "Phrase"),
    ("THE BALL IS IN YOUR COURT", "Phrase"),
    ("THE BEST OF BOTH WORLDS", "Phrase"),
    ("THE EARLY BIRD CATCHES THE WORM", "Phrase"),
    ("THE LAST STRAW", "Phrase"),
    ("THE POT CALLING THE KETTLE BLACK", "Phrase"),
    ("THE STRAW THAT BROKE THE CAMELS BACK", "Phrase"),
    ("THE TIP OF THE ICEBERG", "Phrase"),
    ("THE WHOLE NINE YARDS", "Phrase"),
    ("THE WRITING IS ON THE WALL", "Phrase"),
    ("THROUGH THICK AND THIN", "Phrase"),
    ("THROW CAUTION TO THE WIND", "Phrase"),
    ("THROWING IN THE TOWEL", "Phrase"),
    ("TURN OVER A NEW LEAF", "Phrase"),
    ("TWO PEAS IN A POD", "Phrase"),
    ("UNDER THE WEATHER", "Phrase"),
    ("WALKING ON EGGSHELLS", "Phrase"),
    ("WHEN PIGS FLY", "Phrase"),
    ("WOLF IN SHEEPS CLOTHING", "Phrase"),
    ("YOU CANT JUDGE A BOOK BY ITS COVER", "Phrase"),

    # -------------------------------------------------------------------------
    # Place
    # -------------------------------------------------------------------------

    ("ABANDONED DRIVE IN THEATER", "Place"),
    ("ABANDONED TRAIN STATION", "Place"),
    ("BACK ALLEY BEHIND THE BOWLING ALLEY", "Place"),
    ("BACK CORNER BOOTH", "Place"),
    ("BACK NINE", "Place"),
    ("BACK NINE OF THE GOLF COURSE", "Place"),
    ("BACK OF THE AMBULANCE", "Place"),
    ("BACK OF THE BUS", "Place"),
    ("BACK OF THE CAVE", "Place"),
    ("BACK OF THE CLOSET", "Place"),
    ("BACK ROOM OF THE PAWNSHOP", "Place"),
    ("BOTTOM OF THE BARREL", "Place"),
    ("BOTTOM OF THE GARDEN", "Place"),
    ("BOTTOM OF THE HILL", "Place"),
    ("BOTTOM OF THE OCEAN", "Place"),
    ("BOTTOM OF THE STAIRWELL", "Place"),
    ("BREAK ROOM", "Place"),
    ("CENTER OF THE MAZE", "Place"),
    ("COAT CHECK", "Place"),
    ("CORNER COFFEE SHOP", "Place"),
    ("CORNER OF THE RING", "Place"),
    ("CROWS NEST", "Place"),
    ("DEAD END", "Place"),
    ("DEEP END OF THE POOL", "Place"),
    ("DUSTY ATTIC CORNER", "Place"),
    ("DUSTY COUNTRY ROAD", "Place"),
    ("EDGE OF THE CLIFF", "Place"),
    ("EDGE OF THE MAP", "Place"),
    ("EMPTY SWIMMING POOL", "Place"),
    ("END OF THE LINE", "Place"),
    ("END OF THE PIER", "Place"),
    ("END OF THE RAINBOW", "Place"),
    ("END ZONE", "Place"),
    ("FIRE ESCAPE LANDING", "Place"),
    ("FORK IN THE ROAD", "Place"),
    ("FORGOTTEN CORNER OF THE LIBRARY", "Place"),
    ("FORGOTTEN GARDEN BEHIND THE CHURCH", "Place"),
    ("FORGOTTEN SUBWAY PLATFORM", "Place"),
    ("GREEN ROOM", "Place"),
    ("HAUNTED LIGHTHOUSE", "Place"),
    ("HAY BARN", "Place"),
    ("HEART OF THE CITY", "Place"),
    ("HIDDEN CLEARING IN THE WOODS", "Place"),
    ("HOME BASE", "Place"),
    ("LAST BOOTH IN THE GREASY SPOON", "Place"),
    ("LITTLE LEAGUE BASEBALL FIELD", "Place"),
    ("LOCKED WING OF THE HOSPITAL", "Place"),
    ("LOST AND FOUND", "Place"),
    ("LOST LUGGAGE AREA", "Place"),
    ("MIDNIGHT DINER", "Place"),
    ("MOUTH OF THE RIVER", "Place"),
    ("MUDDY RIVERBANK", "Place"),
    ("NEIGHBORHOOD SWIMMING HOLE", "Place"),
    ("OBSERVATION DECK AT DAWN", "Place"),
    ("OLD COVERED BRIDGE", "Place"),
    ("OLD FISHING DOCK", "Place"),
    ("OLD NEIGHBORHOOD BARBERSHOP", "Place"),
    ("OVERFLOW PARKING LOT", "Place"),
    ("OVERGROWN CEMETERY PATH", "Place"),
    ("PAYPHONE ON THE CORNER", "Place"),
    ("PIT STOP", "Place"),
    ("POND IN THE PARK", "Place"),
    ("ROOFTOP GARDEN", "Place"),
    ("SAFE HOUSE", "Place"),
    ("SIDE OF THE ROAD", "Place"),
    ("STORM CELLAR DOOR", "Place"),
    ("SUPPLY CLOSET", "Place"),
    ("THE BOILER ROOM", "Place"),
    ("THE PENALTY BOX", "Place"),
    ("THE WAITING ROOM", "Place"),
    ("THIRD FLOOR OF THE PARKING GARAGE", "Place"),
    ("TICKET BOOTH AT THE FAIR", "Place"),
    ("TOP BUNK", "Place"),
    ("TOP OF THE FERRIS WHEEL", "Place"),
    ("TOP OF THE FOOD CHAIN", "Place"),
    ("TOP OF THE LIGHTHOUSE", "Place"),
    ("TOP OF THE STAIRS", "Place"),
    ("TOP OF THE WORLD", "Place"),
    ("TOWN SQUARE FOUNTAIN", "Place"),
    ("TREE FORT", "Place"),
    ("UNDER THE BRIDGE", "Place"),
    ("WAR ROOM", "Place"),

    # -------------------------------------------------------------------------
    # Proper Name
    # -------------------------------------------------------------------------

    ("ABRAHAM LINCOLN", "Proper Name"),
    ("AGATHA CHRISTIE", "Proper Name"),
    ("ALAN TURING", "Proper Name"),
    ("ALBERT EINSTEIN", "Proper Name"),
    ("ALEXANDER HAMILTON", "Proper Name"),
    ("ALEXANDER THE GREAT", "Proper Name"),
    ("ALFRED HITCHCOCK", "Proper Name"),
    ("AMELIA EARHART", "Proper Name"),
    ("ANDREW JACKSON", "Proper Name"),
    ("ANNE BOLEYN", "Proper Name"),
    ("ANNE FRANK", "Proper Name"),
    ("BENJAMIN FRANKLIN", "Proper Name"),
    ("BESSIE COLEMAN", "Proper Name"),
    ("BILL GATES", "Proper Name"),
    ("BOOKER T WASHINGTON", "Proper Name"),
    ("BRAM STOKER", "Proper Name"),
    ("CHARLES DARWIN", "Proper Name"),
    ("CHARLES DE GAULLE", "Proper Name"),
    ("CHARLES DICKENS", "Proper Name"),
    ("CHRISTOPHER COLUMBUS", "Proper Name"),
    ("CLARA BARTON", "Proper Name"),
    ("CLEOPATRA", "Proper Name"),
    ("COPERNICUS", "Proper Name"),
    ("CRAZY HORSE", "Proper Name"),
    ("DEAN MARTIN", "Proper Name"),
    ("DIANA ROSS", "Proper Name"),
    ("DOROTHY PARKER", "Proper Name"),
    ("DWIGHT EISENHOWER", "Proper Name"),
    ("EDGAR ALLAN POE", "Proper Name"),
    ("ELEANOR ROOSEVELT", "Proper Name"),
    ("ELIZABETH BLACKWELL", "Proper Name"),
    ("ELLA FITZGERALD", "Proper Name"),
    ("EMILY DICKINSON", "Proper Name"),
    ("ERNEST HEMINGWAY", "Proper Name"),
    ("FLORENCE NIGHTINGALE", "Proper Name"),
    ("FRANK LLOYD WRIGHT", "Proper Name"),
    ("FREDERICK DOUGLASS", "Proper Name"),
    ("FRIDA KAHLO", "Proper Name"),
    ("FYODOR DOSTOEVSKY", "Proper Name"),
    ("GALILEO GALILEI", "Proper Name"),
    ("GENGHIS KHAN", "Proper Name"),
    ("GEORGE ORWELL", "Proper Name"),
    ("GEORGE WASHINGTON", "Proper Name"),
    ("GERONIMO", "Proper Name"),
    ("HARRIET BEECHER STOWE", "Proper Name"),
    ("HARRIET TUBMAN", "Proper Name"),
    ("HELEN KELLER", "Proper Name"),
    ("HENRY DAVID THOREAU", "Proper Name"),
    ("HOMER", "Proper Name"),
    ("IMMANUEL KANT", "Proper Name"),
    ("ISAAC NEWTON", "Proper Name"),
    ("JOAN OF ARC", "Proper Name"),
    ("JOHN ADAMS", "Proper Name"),
    ("JOHN F KENNEDY", "Proper Name"),
    ("JOHN STEINBECK", "Proper Name"),
    ("JOSEPH STALIN", "Proper Name"),
    ("JULIUS CAESAR", "Proper Name"),
    ("LANGSTON HUGHES", "Proper Name"),
    ("LEONARDO DA VINCI", "Proper Name"),
    ("LOUIS ARMSTRONG", "Proper Name"),
    ("LYNDON B JOHNSON", "Proper Name"),
    ("MAHATMA GANDHI", "Proper Name"),
    ("MAO ZEDONG", "Proper Name"),
    ("MARCO POLO", "Proper Name"),
    ("MARIE ANTOINETTE", "Proper Name"),
    ("MARIE CURIE", "Proper Name"),
    ("MARK TWAIN", "Proper Name"),
    ("MARTIN LUTHER KING", "Proper Name"),
    ("MERYL STREEP", "Proper Name"),
    ("MICHELANGELO", "Proper Name"),
    ("MOSES", "Proper Name"),
    ("MOTHER TERESA", "Proper Name"),
    ("NAPOLEON BONAPARTE", "Proper Name"),
    ("NEIL ARMSTRONG", "Proper Name"),
    ("NEIL YOUNG", "Proper Name"),
    ("NELSON MANDELA", "Proper Name"),
    ("NIKOLA TESLA", "Proper Name"),
    ("NIKITA KHRUSHCHEV", "Proper Name"),
    ("OPRAH WINFREY", "Proper Name"),
    ("OTTO VON BISMARCK", "Proper Name"),
    ("PABLO PICASSO", "Proper Name"),
    ("PHILLIS WHEATLEY", "Proper Name"),
    ("PLATO", "Proper Name"),
    ("POCAHONTAS", "Proper Name"),
    ("QUEEN VICTORIA", "Proper Name"),
    ("RALPH WALDO EMERSON", "Proper Name"),
    ("RICHARD NIXON", "Proper Name"),
    ("ROSA PARKS", "Proper Name"),
    ("SIGMUND FREUD", "Proper Name"),
    ("SIMON BOLIVAR", "Proper Name"),
    ("SITTING BULL", "Proper Name"),
    ("SOJOURNER TRUTH", "Proper Name"),
    ("SUSAN B ANTHONY", "Proper Name"),
    ("THEODORE ROOSEVELT", "Proper Name"),
    ("THOMAS EDISON", "Proper Name"),
    ("THOMAS JEFFERSON", "Proper Name"),
    ("THURGOOD MARSHALL", "Proper Name"),
    ("ULYSSES S GRANT", "Proper Name"),
    ("VINCENT VAN GOGH", "Proper Name"),
    ("VIRGINIA WOOLF", "Proper Name"),
    ("VOLTAIRE", "Proper Name"),
    ("WILLIAM SHAKESPEARE", "Proper Name"),
    ("WILLIAM WILBERFORCE", "Proper Name"),
    ("WINSTON CHURCHILL", "Proper Name"),

    # -------------------------------------------------------------------------
    # Proper Place
    # -------------------------------------------------------------------------

    ("ACADIA NATIONAL PARK", "Proper Place"),
    ("ALCATRAZ ISLAND", "Proper Place"),
    ("AMAZON RAIN FOREST", "Proper Place"),
    ("AMAZON RIVER", "Proper Place"),
    ("ANGEL FALLS", "Proper Place"),
    ("APPALACHIAN TRAIL", "Proper Place"),
    ("AREA FIFTY ONE", "Proper Place"),
    ("ARCHES NATIONAL PARK", "Proper Place"),
    ("ARLINGTON NATIONAL CEMETERY", "Proper Place"),
    ("BORA BORA", "Proper Place"),
    ("BOURBON STREET", "Proper Place"),
    ("BRYCE CANYON", "Proper Place"),
    ("BUCKINGHAM PALACE", "Proper Place"),
    ("CAPE CANAVERAL", "Proper Place"),
    ("CAPE COD", "Proper Place"),
    ("CAPE FEAR", "Proper Place"),
    ("CAPE HATTERAS", "Proper Place"),
    ("CAPE OF GOOD HOPE", "Proper Place"),
    ("CENTRAL PARK", "Proper Place"),
    ("CHECKPOINT CHARLIE", "Proper Place"),
    ("CHESAPEAKE BAY", "Proper Place"),
    ("COLOSSEUM", "Proper Place"),
    ("CRATER LAKE", "Proper Place"),
    ("DAYTONA BEACH", "Proper Place"),
    ("DEAD SEA", "Proper Place"),
    ("DEATH VALLEY", "Proper Place"),
    ("DENALI NATIONAL PARK", "Proper Place"),
    ("DEVILS TOWER", "Proper Place"),
    ("EIFFEL TOWER", "Proper Place"),
    ("EMPIRE STATE BUILDING", "Proper Place"),
    ("ENGLISH CHANNEL", "Proper Place"),
    ("FLORIDA EVERGLADES", "Proper Place"),
    ("FLORIDA KEYS", "Proper Place"),
    ("FORBIDDEN CITY", "Proper Place"),
    ("FRENCH QUARTER", "Proper Place"),
    ("GALAPAGOS ISLANDS", "Proper Place"),
    ("GLACIER NATIONAL PARK", "Proper Place"),
    ("GOBI DESERT", "Proper Place"),
    ("GOLDEN GATE BRIDGE", "Proper Place"),
    ("GRAND CANYON", "Proper Place"),
    ("GRAND TETON NATIONAL PARK", "Proper Place"),
    ("GREAT BARRIER REEF", "Proper Place"),
    ("GREAT SMOKY MOUNTAINS", "Proper Place"),
    ("GREAT WALL OF CHINA", "Proper Place"),
    ("GULF OF MEXICO", "Proper Place"),
    ("HOOVER DAM", "Proper Place"),
    ("HUDSON RIVER", "Proper Place"),
    ("INCA TRAIL", "Proper Place"),
    ("ISLE OF CAPRI", "Proper Place"),
    ("LAKE BAIKAL", "Proper Place"),
    ("LAKE ERIE", "Proper Place"),
    ("LAKE HURON", "Proper Place"),
    ("LAKE MICHIGAN", "Proper Place"),
    ("LAKE TAHOE", "Proper Place"),
    ("LIBERTY BELL", "Proper Place"),
    ("LINCOLN MEMORIAL", "Proper Place"),
    ("LOUISIANA BAYOU", "Proper Place"),
    ("MACHU PICCHU", "Proper Place"),
    ("MISSISSIPPI DELTA", "Proper Place"),
    ("MISSISSIPPI RIVER", "Proper Place"),
    ("MOJAVE DESERT", "Proper Place"),
    ("MONT BLANC", "Proper Place"),
    ("MONUMENT VALLEY", "Proper Place"),
    ("MOUNT EVEREST", "Proper Place"),
    ("MOUNT FUJI", "Proper Place"),
    ("MOUNT KILIMANJARO", "Proper Place"),
    ("MOUNT OLYMPUS", "Proper Place"),
    ("MOUNT RUSHMORE", "Proper Place"),
    ("MOUNT SAINT HELENS", "Proper Place"),
    ("MOUNT VESUVIUS", "Proper Place"),
    ("MOUNT WHITNEY", "Proper Place"),
    ("NIAGARA FALLS", "Proper Place"),
    ("NILE RIVER", "Proper Place"),
    ("NORTH POLE", "Proper Place"),
    ("NORWEGIAN FJORDS", "Proper Place"),
    ("PACIFIC CREST TRAIL", "Proper Place"),
    ("PALACE OF VERSAILLES", "Proper Place"),
    ("PALM BEACH", "Proper Place"),
    ("PANAMA CANAL", "Proper Place"),
    ("PATAGONIA WILDERNESS", "Proper Place"),
    ("RED SEA", "Proper Place"),
    ("ROCKY MOUNTAIN NATIONAL PARK", "Proper Place"),
    ("ROCKY MOUNTAINS", "Proper Place"),
    ("SAHARA DESERT", "Proper Place"),
    ("SCOTTISH HIGHLANDS", "Proper Place"),
    ("SEQUOIA NATIONAL PARK", "Proper Place"),
    ("SERENGETI NATIONAL PARK", "Proper Place"),
    ("SHENANDOAH VALLEY", "Proper Place"),
    ("SILICON VALLEY", "Proper Place"),
    ("SOUTH POLE", "Proper Place"),
    ("STATUE OF LIBERTY", "Proper Place"),
    ("STONEHENGE", "Proper Place"),
    ("STRAIT OF GIBRALTAR", "Proper Place"),
    ("SUEZ CANAL", "Proper Place"),
    ("SWISS ALPS", "Proper Place"),
    ("SYDNEY OPERA HOUSE", "Proper Place"),
    ("TAJ MAHAL", "Proper Place"),
    ("THE PARTHENON", "Proper Place"),
    ("TIMES SQUARE", "Proper Place"),
    ("VICTORIA FALLS", "Proper Place"),
    ("WALL STREET", "Proper Place"),
    ("WASHINGTON MONUMENT", "Proper Place"),
    ("WHITE CLIFFS OF DOVER", "Proper Place"),
    ("YELLOWSTONE NATIONAL PARK", "Proper Place"),
    ("ZION NATIONAL PARK", "Proper Place"),

    # -------------------------------------------------------------------------
    # Thing
    # -------------------------------------------------------------------------

    ("ALARM CLOCK", "Thing"),
    ("BATH MAT", "Thing"),
    ("BASKETBALL HOOP", "Thing"),
    ("BED SHEET", "Thing"),
    ("BELT BUCKLE", "Thing"),
    ("BIKE LOCK", "Thing"),
    ("BIRTHDAY CAKE", "Thing"),
    ("BOOK BAG", "Thing"),
    ("BOOK MARK", "Thing"),
    ("BREAD BOX", "Thing"),
    ("BUBBLE WRAP", "Thing"),
    ("BULLETIN BOARD", "Thing"),
    ("CANDLE STICK", "Thing"),
    ("CAR KEY", "Thing"),
    ("CEILING FAN", "Thing"),
    ("COAT HANGER", "Thing"),
    ("COFFEE MUG", "Thing"),
    ("COIN PURSE", "Thing"),
    ("DISH RAG", "Thing"),
    ("DISH TOWEL", "Thing"),
    ("DIVING BOARD", "Thing"),
    ("DOOR KNOCKER", "Thing"),
    ("DOOR MAT", "Thing"),
    ("DOOR STOPPER", "Thing"),
    ("ELECTRIC BLANKET", "Thing"),
    ("EXERCISE BIKE", "Thing"),
    ("FIRE ESCAPE", "Thing"),
    ("FIRE EXTINGUISHER", "Thing"),
    ("FIRE PIT", "Thing"),
    ("FISH TANK", "Thing"),
    ("FLIP FLOPS", "Thing"),
    ("FLOWER POT", "Thing"),
    ("GARDEN GNOME", "Thing"),
    ("GARDEN HOSE", "Thing"),
    ("GIFT WRAP", "Thing"),
    ("HAIR TIE", "Thing"),
    ("HALL MIRROR", "Thing"),
    ("HAND FAN", "Thing"),
    ("IRONING BOARD", "Thing"),
    ("JEWELRY BOX", "Thing"),
    ("JUMP ROPE", "Thing"),
    ("KEY CHAIN", "Thing"),
    ("KITCHEN TIMER", "Thing"),
    ("LAVA LAMP", "Thing"),
    ("LIP BALM", "Thing"),
    ("LOADING DOCK", "Thing"),
    ("LUGGAGE TAG", "Thing"),
    ("LUNCH BOX", "Thing"),
    ("MAGNIFYING GLASS", "Thing"),
    ("MAIL BOX", "Thing"),
    ("MOUSE TRAP", "Thing"),
    ("NOTE PAD", "Thing"),
    ("PAPER SHREDDER", "Thing"),
    ("PARKING METER", "Thing"),
    ("PEA COAT", "Thing"),
    ("PENCIL SHARPENER", "Thing"),
    ("PEPPER GRINDER", "Thing"),
    ("PERISCOPE", "Thing"),
    ("PHONE CASE", "Thing"),
    ("PHONE CHARGER", "Thing"),
    ("PICTURE FRAME", "Thing"),
    ("PIGGY BANK", "Thing"),
    ("PILL BOTTLE", "Thing"),
    ("POCKET WATCH", "Thing"),
    ("PORCH SWING", "Thing"),
    ("ROCKING CHAIR", "Thing"),
    ("RUBBER DUCK", "Thing"),
    ("SHOE HORN", "Thing"),
    ("SLEEPING BAG", "Thing"),
    ("SMOKE DETECTOR", "Thing"),
    ("SNOW BLOWER", "Thing"),
    ("SNOW GLOBE", "Thing"),
    ("SPICE RACK", "Thing"),
    ("STAPLE GUN", "Thing"),
    ("STEP STOOL", "Thing"),
    ("SWIMMING POOL", "Thing"),
    ("TEA CUP", "Thing"),
    ("TELESCOPE", "Thing"),
    ("THROW PILLOW", "Thing"),
    ("TOOL CHEST", "Thing"),
    ("TOY BOX", "Thing"),
    ("TROPHY CASE", "Thing"),
    ("WAGON WHEEL", "Thing"),
    ("WEATHER VANE", "Thing"),
    ("WELCOME MAT", "Thing"),
    ("WELCOME SIGN", "Thing"),
    ("WIND CHIME", "Thing"),

    # -------------------------------------------------------------------------
    # What Are You Doing?
    # -------------------------------------------------------------------------

    ("ALPHABETIZING THE SPICE RACK", "What Are You Doing?"),
    ("ASSEMBLING FLAT PACK FURNITURE", "What Are You Doing?"),
    ("AVOIDING EYE CONTACT", "What Are You Doing?"),
    ("BAKING CHOCOLATE CHIP COOKIES", "What Are You Doing?"),
    ("BALANCING THE CHECKBOOK", "What Are You Doing?"),
    ("BLOWING BUBBLES", "What Are You Doing?"),
    ("BUILDING A BLANKET FORT", "What Are You Doing?"),
    ("BUILDING A SANDCASTLE", "What Are You Doing?"),
    ("CALCULATING THE TIP ON A LARGE GROUP BILL", "What Are You Doing?"),
    ("CALLING MOM", "What Are You Doing?"),
    ("CATALOGUING THE RECORD COLLECTION", "What Are You Doing?"),
    ("CATCHING FIREFLIES", "What Are You Doing?"),
    ("CAULKING THE BATHTUB", "What Are You Doing?"),
    ("CHASING YOUR TAIL", "What Are You Doing?"),
    ("CHECKING THE MAIL", "What Are You Doing?"),
    ("CLEANING THE GARAGE", "What Are You Doing?"),
    ("COMPOSTING KITCHEN SCRAPS", "What Are You Doing?"),
    ("COUNTING SHEEP", "What Are You Doing?"),
    ("DEBUGGING COMPUTER CODE", "What Are You Doing?"),
    ("DECLUTTERING THE BASEMENT", "What Are You Doing?"),
    ("DEFENDING YOUR DOCTORAL THESIS", "What Are You Doing?"),
    ("DIGGING A HOLE", "What Are You Doing?"),
    ("DOING THE DISHES", "What Are You Doing?"),
    ("EAVESDROPPING ON THE NEIGHBORS", "What Are You Doing?"),
    ("EATING LUNCH", "What Are You Doing?"),
    ("EXPLAINING QUANTUM PHYSICS TO A CHILD", "What Are You Doing?"),
    ("FEEDING THE DUCKS", "What Are You Doing?"),
    ("FILING YOUR TAXES", "What Are You Doing?"),
    ("FLYING A KITE", "What Are You Doing?"),
    ("FOLDING LAUNDRY", "What Are You Doing?"),
    ("FOLLOWING A COMPLICATED RECIPE", "What Are You Doing?"),
    ("KNITTING A SWEATER", "What Are You Doing?"),
    ("LAMINATING EVERYTHING IN SIGHT", "What Are You Doing?"),
    ("LEARNING TO PLAY GUITAR", "What Are You Doing?"),
    ("LEARNING TO RIDE A BIKE", "What Are You Doing?"),
    ("MAKING BREAKFAST", "What Are You Doing?"),
    ("MOWING THE LAWN", "What Are You Doing?"),
    ("NARRATING YOUR OWN LIFE", "What Are You Doing?"),
    ("NEGOTIATING A HOSTAGE SITUATION", "What Are You Doing?"),
    ("OVERHAULING THE FILING SYSTEM", "What Are You Doing?"),
    ("OVERTHINKING EVERYTHING", "What Are You Doing?"),
    ("PACKING A SUITCASE", "What Are You Doing?"),
    ("PAINTING THE BEDROOM", "What Are You Doing?"),
    ("PARALLEL PARKING A MOVING TRUCK", "What Are You Doing?"),
    ("PERFORMING IN THE SCHOOL TALENT SHOW", "What Are You Doing?"),
    ("PETTING THE CAT", "What Are You Doing?"),
    ("PICKING APPLES", "What Are You Doing?"),
    ("PLANTING SEEDS", "What Are You Doing?"),
    ("POWER WASHING THE DRIVEWAY", "What Are You Doing?"),
    ("PRACTICING THE ACCEPTANCE SPEECH", "What Are You Doing?"),
    ("PRESSING WILDFLOWERS", "What Are You Doing?"),
    ("PRETENDING TO BE BUSY", "What Are You Doing?"),
    ("PRETENDING TO WORK FROM HOME", "What Are You Doing?"),
    ("RAKING LEAVES", "What Are You Doing?"),
    ("READING A GOOD BOOK", "What Are You Doing?"),
    ("REFINISHING THE HARDWOOD FLOORS", "What Are You Doing?"),
    ("REORGANIZING THE PANTRY", "What Are You Doing?"),
    ("REPOTTING THE SUCCULENTS", "What Are You Doing?"),
    ("RESTORING AN OLD PHOTO", "What Are You Doing?"),
    ("REWATCHING THE SAME DOCUMENTARY", "What Are You Doing?"),
    ("REWIRING AN OLD LAMP", "What Are You Doing?"),
    ("ROLLING DOWN A HILL", "What Are You Doing?"),
    ("RUNNING A MARATHON", "What Are You Doing?"),
    ("SCHEDULING BACK TO BACK MEETINGS", "What Are You Doing?"),
    ("SHARPENING ALL THE KNIVES", "What Are You Doing?"),
    ("SHOVELING SNOW", "What Are You Doing?"),
    ("SITTING IN TRAFFIC", "What Are You Doing?"),
    ("SKIPPING STONES", "What Are You Doing?"),
    ("SOLVING A CROSSWORD PUZZLE", "What Are You Doing?"),
    ("SORTING THE RECYCLING", "What Are You Doing?"),
    ("STARGAZING IN THE BACKYARD", "What Are You Doing?"),
    ("STEAM CLEANING THE CARPETS", "What Are You Doing?"),
    ("STUDYING FOR THE BAR EXAM", "What Are You Doing?"),
    ("TAKING A BUBBLE BATH", "What Are You Doing?"),
    ("TAKING A NAP", "What Are You Doing?"),
    ("TAKING A SELFIE", "What Are You Doing?"),
    ("TAKING OUT THE TRASH", "What Are You Doing?"),
    ("TEACHING THE DOG A NEW TRICK", "What Are You Doing?"),
    ("TRAINING FOR A TRIATHLON", "What Are You Doing?"),
    ("TRANSLATING AN ANCIENT MANUSCRIPT", "What Are You Doing?"),
    ("UNTANGLING CHRISTMAS LIGHTS", "What Are You Doing?"),
    ("WALKING THE DOG", "What Are You Doing?"),
    ("WATCHING PAINT DRY", "What Are You Doing?"),
    ("WATCHING THE STOCK TICKER", "What Are You Doing?"),
    ("WATCHING THE SUNSET", "What Are You Doing?"),
    ("WATERING THE PLANTS", "What Are You Doing?"),
    ("WEATHERPROOFING THE WINDOWS", "What Are You Doing?"),
    ("WINDOW SHOPPING DOWNTOWN", "What Are You Doing?"),
    ("WRITING IN A JOURNAL", "What Are You Doing?"),
]